export interface Civilization {
  "name": string;
  "hand cannoneer": boolean;
  "eagle scout": boolean;
  "barracks": boolean;
  "long swordsman": boolean;
  "militia": boolean;
  "man-at-arms": boolean;
  "spearman": boolean;
  "supplies": boolean;
  "archer": boolean;
  "skirmisher": boolean;
  "archery range": boolean;
  "crossbowman": boolean;
  "elite skirmisher": boolean;
  "eagle warrior": boolean;
  "squires": boolean;
  "arson": boolean;
  "arbalester": boolean;
  "two-handed swordsman": boolean;
  "elite eagle warrior": boolean;
  "champion": boolean;
  "siege workshop": boolean;
  "battering ram": boolean;
  "capped ram": boolean;
  "siege ram": boolean;
  "mangonel": boolean;
  "onager": boolean;
  "siege onager": boolean;
  "scorpion": boolean;
  "siege tower": boolean;
  "blacksmith": boolean;
  "padded archer armor": boolean;
  "leather archer armor": boolean;
  "fletching": boolean;
  "bodkin arrow": boolean;
  "bracer": boolean;
  "forging": boolean;
  "iron casting": boolean;
  "blast furnace": boolean;
  "scale mail armor": boolean;
  "chain mail armor": boolean;
  "plate mail armor": boolean;
  "dock": boolean;
  "fishing ship": boolean;
  "transport ship": boolean;
  "fire galley": boolean;
  "fire ship": boolean;
  "fast fire ship": boolean;
  "trade cog": boolean;
  "gillnets": boolean;
  "demolition raft": boolean;
  "demolition ship": boolean;
  "galley": boolean;
  "war galley": boolean;
  "careening": boolean;
  "dry dock": boolean;
  "shipwright": boolean;
  "fish trap": boolean;
  "university": boolean;
  "fortified wall": boolean;
  "chemistry": boolean;
  "ballistics": boolean;
  "siege engineers": boolean;
  "guard tower": boolean;
  "heated shot": boolean;
  "arrowslits": boolean;
  "murder holes": boolean;
  "treadmill crane": boolean;
  "outpost": boolean;
  "watch tower": boolean;
  "palisade wall": boolean;
  "palisade gate": boolean;
  "gate": boolean;
  "stone wall": boolean;
  "castle": boolean;
  "jaguar warrior": boolean;
  "elite jaguar": boolean;
  "petard": boolean;
  "trebuchet": boolean;
  "sappers": boolean;
  "conscription": boolean;
  "spies/treason": boolean;
  "monastery": boolean;
  "monk": boolean;
  "faith": boolean;
  "redemption": boolean;
  "illumination": boolean;
  "atonement": boolean;
  "block printing": boolean;
  "herbal medicine": boolean;
  "theocracy": boolean;
  "heresy": boolean;
  "sanctity": boolean;
  "fervor": boolean;
  "house": boolean;
  "town center": boolean;
  "villager": boolean;
  "town watch": boolean;
  "town patrol": boolean;
  "feudal age": boolean;
  "castle age": boolean;
  "imperial age": boolean;
  "loom": boolean;
  "wheelbarrow": boolean;
  "hand cart": boolean;
  "wonder": boolean;
  "mining camp": boolean;
  "gold mining": boolean;
  "gold shaft mining": boolean;
  "stone mining": boolean;
  "stone shaft mining": boolean;
  "lumber camp": boolean;
  "double-bit axe": boolean;
  "bow saw": boolean;
  "mill": boolean;
  "market": boolean;
  "trade cart": boolean;
  "coinage": boolean;
  "caravan": boolean;
  "banking": boolean;
  "farm": boolean;
  "horse collar": boolean;
  "heavy plow": boolean;
  "crop rotation": boolean;
}